name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: <script src="https://gist.github.com/jiohjung98/cdb4058287fb3af32a27ce531241f9a0.js"></script>
          TIMEZONE: Asia/Taipei
